/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewSecretaria;

import DAO.AgendamentoDAO;
import classes.Agendamento;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bruno
 */
public class AgendaSecretaria extends javax.swing.JInternalFrame {

    /**
     * Creates new form AgendaSecretaria
     */
    private static boolean agFechada = true;

    public AgendaSecretaria() {
        if (agFechada) {
            agFechada = false;
            initComponents();
        } else {
            JOptionPane.showMessageDialog(null, "ERRO: Janela de agenda já está aberta!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        calendario = new com.toedter.calendar.JCalendar();
        btnBuscaNome = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        txtNomePaciente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBuscaData = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelaAgendamento = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Agenda");
        setMinimumSize(new java.awt.Dimension(1100, 600));
        setPreferredSize(new java.awt.Dimension(1100, 600));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Agendamentos"));

        btnBuscaNome.setText("Buscar pelo Nome");
        btnBuscaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaNomeActionPerformed(evt);
            }
        });

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        jLabel1.setText("Busca:");

        btnBuscaData.setText("Buscar pela Data");
        btnBuscaData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaDataActionPerformed(evt);
            }
        });

        tabelaAgendamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Horas", "Nome", "Tipo", "Atendida"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaAgendamento.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaAgendamento.getTableHeader().setResizingAllowed(false);
        tabelaAgendamento.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(tabelaAgendamento);
        if (tabelaAgendamento.getColumnModel().getColumnCount() > 0) {
            tabelaAgendamento.getColumnModel().getColumn(0).setMinWidth(100);
            tabelaAgendamento.getColumnModel().getColumn(0).setPreferredWidth(100);
            tabelaAgendamento.getColumnModel().getColumn(0).setMaxWidth(100);
            tabelaAgendamento.getColumnModel().getColumn(1).setMinWidth(80);
            tabelaAgendamento.getColumnModel().getColumn(1).setPreferredWidth(80);
            tabelaAgendamento.getColumnModel().getColumn(1).setMaxWidth(80);
            tabelaAgendamento.getColumnModel().getColumn(2).setMinWidth(220);
            tabelaAgendamento.getColumnModel().getColumn(3).setMinWidth(100);
            tabelaAgendamento.getColumnModel().getColumn(3).setPreferredWidth(120);
            tabelaAgendamento.getColumnModel().getColumn(4).setMinWidth(90);
            tabelaAgendamento.getColumnModel().getColumn(4).setPreferredWidth(90);
            tabelaAgendamento.getColumnModel().getColumn(4).setMaxWidth(90);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNomePaciente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscaData, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscaData))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscaNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar)
                    .addComponent(btnEditar)
                    .addComponent(btnRemover))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        agFechada = true;
    }//GEN-LAST:event_formInternalFrameClosed

    private void btnBuscaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaNomeActionPerformed
        readJTabelaNome();
    }//GEN-LAST:event_btnBuscaNomeActionPerformed

    private void btnBuscaDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaDataActionPerformed
        readJTabelaData();
    }//GEN-LAST:event_btnBuscaDataActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        PrincipalSecretaria.abrirAgendamento();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        if (tabelaAgendamento.getSelectedRow() != -1) {

            String dataDeletar = (String) tabelaAgendamento.getValueAt(tabelaAgendamento.getSelectedRow(), 0);
            String horaDeletar = (String) tabelaAgendamento.getValueAt(tabelaAgendamento.getSelectedRow(), 1);
            
            AgendamentoDAO agen = new AgendamentoDAO();
            agen.delete(dataDeletar, horaDeletar);

            readJTabelaNome();

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um Paciente para excluir!");
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (tabelaAgendamento.getSelectedRow() != -1) {

            String dataEditar = (String) tabelaAgendamento.getValueAt(tabelaAgendamento.getSelectedRow(), 0);
            String horaEditar = (String) tabelaAgendamento.getValueAt(tabelaAgendamento.getSelectedRow(), 1);
            
            AgendamentoDAO agen = new AgendamentoDAO();
            Agendamento a = agen.pesquisaAgendamento(dataEditar, horaEditar);
            
            
            PrincipalSecretaria.editarAgendamento(a);

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um Paciente para editar!");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    public void readJTabelaNome() {
        DefaultTableModel m = (DefaultTableModel) tabelaAgendamento.getModel();
        m.setNumRows(0);
        AgendamentoDAO agen = new AgendamentoDAO();

        for (Agendamento a : agen.readNome(txtNomePaciente.getText())) {

            //Convertendo o formato da data APENAS para a impressao
            //SimpleDateFormat sm = new SimpleDateFormat("dd/MM/yyyy");
            //String auxiliarData = sm.format(a.getDataAgendamento());

            m.addRow(new Object[]{
               a.getDataAgendamento(),
                a.getHoraAgendamento(),
                a.getNomePaciente(),
                a.getTipoAgendamento(),
                a.getPresenca(),});
        }

    }

    public void readJTabelaData() {
        DefaultTableModel m = (DefaultTableModel) tabelaAgendamento.getModel();
        m.setNumRows(0);
        AgendamentoDAO agen = new AgendamentoDAO();

        for (Agendamento a : agen.readData(calendario.getDate())) {

            //Convertendo o formato da data APENAS para a impressao
            //SimpleDateFormat sm = new SimpleDateFormat("dd/MM/yyyy");
            //String auxiliarData = sm.format(a.getDataAgendamento());

            m.addRow(new Object[]{
                a.getDataAgendamento(),
                a.getHoraAgendamento(),
                a.getNomePaciente(),
                a.getTipoAgendamento(),
                a.getPresenca(),
            });
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnBuscaData;
    private javax.swing.JButton btnBuscaNome;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnRemover;
    private com.toedter.calendar.JCalendar calendario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tabelaAgendamento;
    private javax.swing.JTextField txtNomePaciente;
    // End of variables declaration//GEN-END:variables
}
