/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewSecretaria;

import classes.Agendamento;
import classes.Paciente;
import javax.swing.JOptionPane;

/**
 *
 * @author bruno
 */
public class PrincipalSecretaria extends javax.swing.JFrame {

    private static ListarPacientes listPac = null;

    /**
     * Creates new form PrincipalSecretaria
     */
    public PrincipalSecretaria() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpSecretaria = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuAgenda = new javax.swing.JMenuItem();
        jMenuPaciente = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Secretária");
        setPreferredSize(new java.awt.Dimension(1100, 1000));

        jdpSecretaria.setToolTipText("");
        jdpSecretaria.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jdpSecretaria.setPreferredSize(new java.awt.Dimension(1100, 1000));

        jMenu1.setText("Opções");

        jMenuAgenda.setText("Agenda");
        jMenuAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAgendaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuAgenda);

        jMenuPaciente.setText("Paciente");
        jMenuPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPacienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuPaciente);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpSecretaria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpSecretaria, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1110, 761);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPacienteActionPerformed
        ListarPacientes obj = new ListarPacientes();
        listPac = obj;
        jdpSecretaria.add(obj);
        obj.setVisible(true);

    }//GEN-LAST:event_jMenuPacienteActionPerformed

    private void jMenuAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAgendaActionPerformed
        AgendaSecretaria obj = new AgendaSecretaria();
        jdpSecretaria.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuAgendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void executar() {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalSecretaria().setVisible(true);
            }
        });
    }

    public static void abrirCadastro() {

        CadastrarPaciente obj = new CadastrarPaciente();
        jdpSecretaria.add(obj);
        obj.setVisible(true);

    }

    public static void abrirAgendamento() {

        CadastrarAgendamento obj = new CadastrarAgendamento();
        jdpSecretaria.add(obj);
        obj.setVisible(true);

    }
    
    public static void editarAgendamento(Agendamento a) {
        
        CadastrarAgendamento obj = new CadastrarAgendamento(a);
        jdpSecretaria.add(obj);
        obj.setVisible(true);

    }
    
    public static void editarCadastro(Paciente p) {

        CadastrarPaciente obj = new CadastrarPaciente(p, listPac);

        jdpSecretaria.add(obj);
        obj.setVisible(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuAgenda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuPaciente;
    private static javax.swing.JDesktopPane jdpSecretaria;
    // End of variables declaration//GEN-END:variables
}
